/*
 * This file is generated by jOOQ.
 */
package com.invitae.lab.platform.variant.schema.jooq;


import com.invitae.lab.platform.variant.schema.jooq.tables.Variant;
import com.invitae.lab.platform.variant.schema.jooq.tables.records.VariantRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<VariantRecord> VARIANT_PKEY = UniqueKeys0.VARIANT_PKEY;
    public static final UniqueKey<VariantRecord> VARIANT_GENE_NUCLEOTIDE_CHANGE_PROTEIN_CHANGE_KEY = UniqueKeys0.VARIANT_GENE_NUCLEOTIDE_CHANGE_PROTEIN_CHANGE_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<VariantRecord> VARIANT_PKEY = Internal.createUniqueKey(Variant.VARIANT, "variant_pkey", new TableField[] { Variant.VARIANT.VARIANT_ID }, true);
        public static final UniqueKey<VariantRecord> VARIANT_GENE_NUCLEOTIDE_CHANGE_PROTEIN_CHANGE_KEY = Internal.createUniqueKey(Variant.VARIANT, "variant_gene_nucleotide_change_protein_change_key", new TableField[] { Variant.VARIANT.GENE, Variant.VARIANT.NUCLEOTIDE_CHANGE, Variant.VARIANT.PROTEIN_CHANGE }, true);
    }
}
