/*
 * This file is generated by jOOQ.
 */
package com.invitae.lab.platform.variant.schema.jooq;


import com.invitae.lab.platform.variant.schema.jooq.tables.Variant;


/**
 * Convenience access to all tables in public
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.variant</code>.
     */
    public static final Variant VARIANT = Variant.VARIANT;
}
