/*
 * This file is generated by jOOQ.
 */
package com.invitae.lab.platform.variant.schema.jooq.tables.records;


import com.invitae.lab.platform.variant.schema.jooq.tables.Variant;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VariantRecord extends UpdatableRecordImpl<VariantRecord> implements Record6<UUID, String, String, String, LocalDate, LocalDateTime> {

    private static final long serialVersionUID = -1178554675;

    /**
     * Setter for <code>public.variant.variant_id</code>.
     */
    public VariantRecord setVariantId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.variant.variant_id</code>.
     */
    public UUID getVariantId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.variant.gene</code>.
     */
    public VariantRecord setGene(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.variant.gene</code>.
     */
    public String getGene() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.variant.nucleotide_change</code>.
     */
    public VariantRecord setNucleotideChange(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.variant.nucleotide_change</code>.
     */
    public String getNucleotideChange() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.variant.protein_change</code>.
     */
    public VariantRecord setProteinChange(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.variant.protein_change</code>.
     */
    public String getProteinChange() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.variant.last_evaluated</code>.
     */
    public VariantRecord setLastEvaluated(LocalDate value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.variant.last_evaluated</code>.
     */
    public LocalDate getLastEvaluated() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.variant.created</code>.
     */
    public VariantRecord setCreated(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.variant.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, String, LocalDate, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, String, LocalDate, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Variant.VARIANT.VARIANT_ID;
    }

    @Override
    public Field<String> field2() {
        return Variant.VARIANT.GENE;
    }

    @Override
    public Field<String> field3() {
        return Variant.VARIANT.NUCLEOTIDE_CHANGE;
    }

    @Override
    public Field<String> field4() {
        return Variant.VARIANT.PROTEIN_CHANGE;
    }

    @Override
    public Field<LocalDate> field5() {
        return Variant.VARIANT.LAST_EVALUATED;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Variant.VARIANT.CREATED;
    }

    @Override
    public UUID component1() {
        return getVariantId();
    }

    @Override
    public String component2() {
        return getGene();
    }

    @Override
    public String component3() {
        return getNucleotideChange();
    }

    @Override
    public String component4() {
        return getProteinChange();
    }

    @Override
    public LocalDate component5() {
        return getLastEvaluated();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public UUID value1() {
        return getVariantId();
    }

    @Override
    public String value2() {
        return getGene();
    }

    @Override
    public String value3() {
        return getNucleotideChange();
    }

    @Override
    public String value4() {
        return getProteinChange();
    }

    @Override
    public LocalDate value5() {
        return getLastEvaluated();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public VariantRecord value1(UUID value) {
        setVariantId(value);
        return this;
    }

    @Override
    public VariantRecord value2(String value) {
        setGene(value);
        return this;
    }

    @Override
    public VariantRecord value3(String value) {
        setNucleotideChange(value);
        return this;
    }

    @Override
    public VariantRecord value4(String value) {
        setProteinChange(value);
        return this;
    }

    @Override
    public VariantRecord value5(LocalDate value) {
        setLastEvaluated(value);
        return this;
    }

    @Override
    public VariantRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public VariantRecord values(UUID value1, String value2, String value3, String value4, LocalDate value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VariantRecord
     */
    public VariantRecord() {
        super(Variant.VARIANT);
    }

    /**
     * Create a detached, initialised VariantRecord
     */
    public VariantRecord(UUID variantId, String gene, String nucleotideChange, String proteinChange, LocalDate lastEvaluated, LocalDateTime created) {
        super(Variant.VARIANT);

        set(0, variantId);
        set(1, gene);
        set(2, nucleotideChange);
        set(3, proteinChange);
        set(4, lastEvaluated);
        set(5, created);
    }
}
